"""Regenerate `docs/reference/` from the registries the running code holds.

Four pages, four authorities, and not one hand-written line in any of them:
`FEATURES`, `OPS`, the two converter registries beside `TRACK_SCHEMAS`, and the
Typer app behind the `mosaic` console script. Each is already the authority at
run time -- the CLI's own discovery commands read exactly these -- so a reference
page derived from anything else is a second answer, and second answers drift.

They had drifted. Three hand-maintained feature lists disagreed with each other
and all three with the registry: the site's landing page said "~30", the feature
library page said "40+" and listed 28, the README listed a subset, and `FEATURES`
held 44. Twelve features appeared in none of them.

**Why the output is committed rather than produced during `mkdocs build`.**
`FEATURES` is filled by import side effects in
`behavior/feature_library/__init__.py`, so the registry is exactly as complete as
the environment that imported it. A generator running inside the build, in an
environment missing one dependency, emits a *shorter* list -- and `mkdocs build
--strict` still reports success, because a feature that never registered raises
no warning. Nothing about the page would look wrong. Diffing against a committed
file turns that silence into a failed job that names what went missing, and it
puts the docs change in the same review as the code change that caused it.

**Why a reduced parameter table rather than the raw schema.** The JSON-Schema
document moves whenever pydantic changes how it spells a union or where it hangs
a constraint, and every such move would fail `--check` on an unrelated pull
request. Name, type, default and constraints absorb that. The description is
mosaic's own text, published by `Declared` and by nothing else -- the `Field`
spelling is refused -- so it moves when an author changes it and at no other
time.

Writes nothing by default, like `gen_third_party_inventory.py` beside it.
`--check` regenerates in memory and prints a unified diff of whatever no longer
matches, which is what CI runs; `--write` is the one mode that touches the tree.

No timestamp, no tool version and no package version appears in the output.
Any of them would make every regeneration a diff, which is the fastest way to
teach people to skip the check.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections.abc import Callable, Mapping
from inspect import cleandoc
from pathlib import Path
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    # Under `from __future__ import annotations` this is never evaluated at
    # runtime, which keeps the script's import as light as the deferred
    # registry imports below make it.
    from mosaic.core.json_value import JsonValue

REPOSITORY_ROOT: Final = Path(__file__).resolve().parent.parent
REFERENCE_ROOT: Final = REPOSITORY_ROOT / "docs" / "reference"

BANNER: Final = (
    "<!-- Generated by scripts/gen_docs_reference.py from the live registries.\n"
    "     Do not edit by hand: run `python scripts/gen_docs_reference.py --write`. -->"
)

# Ordered, because a reader scans top to bottom and per-frame is where nearly
# everyone starts. `None` is last and deliberately not folded into a bland
# "other": two features declare no category, and naming that reads as a gap in
# the code rather than as a design.
CATEGORY_TITLES: Final[tuple[tuple[str | None, str], ...]] = (
    ("per-frame", "Per-frame and per-sequence"),
    ("summary", "Per-sequence summary"),
    ("global", "Global (fit once, apply everywhere)"),
    ("media", "Media"),
    ("tag", "Tag"),
    (None, "No category declared"),
)

UNCATEGORIZED_NOTE: Final = (
    '!!! warning "These features declare no category"\n'
    "\n"
    "    They set no `category` class attribute, so `mosaic features list`\n"
    "    reports `null` and no grouping can place them. Declaring one is a\n"
    "    one-line change in the feature class.\n"
)

# Both generated pages that carry parameter tables say this once, rather than
# spending table width on it in every row.
TABLE_LEGEND: Final[tuple[str, ...]] = (
    "In the tables below, **_required_** means the parameter has no default and must",
    "be supplied. **_constructed_** means it is optional but its default is built by a",
    "factory rather than being a literal, so there is no value to print.",
    "",
)

DOMAIN_TITLES: Final[tuple[tuple[str, str], ...]] = (
    ("tracking", "Tracking"),
    ("media", "Media"),
)

# Ordered so a page reads constraint-tightest first, and closed so an unknown
# keyword is dropped rather than rendered as a bare JSON fragment.
CONSTRAINT_LABELS: Final[tuple[tuple[str, str], ...]] = (
    ("minimum", ">="),
    ("exclusiveMinimum", ">"),
    ("maximum", "<="),
    ("exclusiveMaximum", "<"),
    ("minLength", "min length"),
    ("maxLength", "max length"),
    ("minItems", "min items"),
    ("maxItems", "max items"),
    ("pattern", "matches"),
)


def summary_line(obj: type) -> str:
    """The first paragraph of a docstring, flattened to one line.

    Seven ops carry no docstring at all. They render as an empty cell rather
    than as the `Op` base class's text, because inheriting a parent's summary
    would state something false about the subclass.
    """
    own = obj.__dict__.get("__doc__")
    if not isinstance(own, str) or not own.strip():
        return ""
    return cleandoc(own).split("\n\n", 1)[0].replace("\n", " ").strip()


def escape_cell(text: str) -> str:
    """A table cell that cannot break the table it sits in."""
    return text.replace("|", "\\|").replace("\n", " ")


def model_name(raw: str) -> str:
    """A `$defs` key, tidied without being renamed.

    pydantic spells a parameterized generic by flattening its arguments into the
    key -- `ArtifactSpec_ParquetLoadSpec_DataFrame_` -- and the trailing
    separator reads as a typo. Only that is trimmed, and the same function is
    used for the type column and for the collapsed block's heading, so the two
    always name the same thing.
    """
    return raw.rstrip("_")


def type_text(spec: Mapping[str, JsonValue]) -> str:
    """One JSON-Schema property reduced to a readable type expression.

    `anyOf` is what pydantic emits for `X | None`, which most optional fields
    are; echoing the full two-branch union would drown the table. `oneOf` is
    what a tagged union emits, and its branches are the models a client picks
    between. A `$ref` names a nested model whose own table follows in a
    collapsed block.
    """
    ref = spec.get("$ref")
    if isinstance(ref, str):
        return f"`{model_name(ref.rsplit('/', 1)[-1])}`"
    for key in ("anyOf", "oneOf"):
        variants = spec.get(key)
        if isinstance(variants, list):
            # `dict.fromkeys` rather than `set`, to keep the declared branch
            # order: a set would reorder `str | None` between runs and flap
            # `--check`.
            parts = [type_text(v) for v in variants if isinstance(v, dict)]
            return " | ".join(dict.fromkeys(parts))
    if "const" in spec:
        return f"`{json.dumps(spec['const'])}`"
    choices = spec.get("enum")
    if isinstance(choices, list):
        return " | ".join(f"`{json.dumps(c)}`" for c in choices)
    fixed = spec.get("prefixItems")
    if isinstance(fixed, list):
        inner = ", ".join(type_text(f) for f in fixed if isinstance(f, dict))
        return f"tuple of ({inner})" if inner else "`tuple`"
    kind = spec.get("type")
    if kind == "array":
        items = spec.get("items")
        inner = type_text(items) if isinstance(items, dict) else "any"
        return f"list of {inner}"
    if kind == "object":
        return "`object`"
    if kind == "null":
        return "`None`"
    if isinstance(kind, str):
        return f"`{kind}`"
    return "any"


def constraints_text(spec: Mapping[str, JsonValue]) -> str:
    return ", ".join(
        f"{label} `{spec[key]}`" for key, label in CONSTRAINT_LABELS if key in spec
    )


def description_text(spec: Mapping[str, JsonValue]) -> str:
    """A field's declared prose, its unit, and why nothing reads it.

    Every key comes from `Declared`, which is mosaic's own text rather than
    anything pydantic spells, so none moves when a pydantic release changes
    how it renders a union. A field declared `NEEDS_DESCRIPTION` renders an empty
    cell, which is what it has to say.

    `x-mosaic-unwired` is rendered because this table is the page a reader
    consults before setting a parameter. Printing the prose alone would describe
    a control that changes nothing and say nothing about it.
    """
    description = str(spec.get("description", "") or "").strip()
    unit = str(spec.get("x-mosaic-unit", "") or "").strip()
    unwired = str(spec.get("x-mosaic-unwired", "") or "").strip()
    if description and unit:
        text = f"{description} [{unit}]"
    else:
        text = description or (f"[{unit}]" if unit else "")
    if not unwired:
        return text
    note = f"**Unwired:** {unwired}."
    return f"{text} {note}" if text else note


def params_table(schema: Mapping[str, JsonValue], depth: int = 0) -> list[str]:
    """The properties table, plus one collapsed table per nested model.

    Most feature params carry `$defs`. Inlining them would put dozens of rows
    under a feature that has four of its own, so each nested model gets a
    `pymdownx.details` block that opens on demand.
    """
    lines: list[str] = []
    properties = schema.get("properties")
    if isinstance(properties, dict) and properties:
        # The schema's own `required` list, not the absence of a `default` key.
        # A field declared with `default_factory=` is optional and carries no
        # serializable default, so presence-of-default reports it as required
        # and would tell a reader to pass something the model constructs itself.
        required_names = schema.get("required")
        required: set[JsonValue] = (
            set(required_names) if isinstance(required_names, list) else set()
        )
        lines += [
            "| Parameter | Type | Default | Constraints | Description |",
            "| --- | --- | --- | --- | --- |",
        ]
        for name, raw in properties.items():
            spec: Mapping[str, JsonValue] = raw if isinstance(raw, dict) else {}
            if name in required:
                default = "_required_"
            elif "default" in spec:
                default = f"`{json.dumps(spec['default'])}`"
            else:
                default = "_constructed_"
            lines.append(
                f"| `{name}` | {escape_cell(type_text(spec))} "
                f"| {escape_cell(default)} | {escape_cell(constraints_text(spec))} "
                f"| {escape_cell(description_text(spec))} |"
            )
        lines.append("")
    else:
        lines += ["No parameters.", ""]

    # Only the top level expands nested models: a `$defs` block is shared by the
    # whole document, so recursing would repeat every definition at every depth.
    nested = schema.get("$defs")
    if depth == 0 and isinstance(nested, dict):
        for raw_name in sorted(nested):
            sub = nested[raw_name]
            if not isinstance(sub, dict):
                continue
            lines.append(f'??? note "`{model_name(raw_name)}`"')
            lines.append("")
            lines += [
                f"    {line}" if line else "" for line in params_table(sub, depth + 1)
            ]
    return lines


def render_features() -> str:
    from mosaic.behavior.feature_library import FEATURES

    grouped: dict[str | None, list[type]] = {}
    for cls in FEATURES.values():
        raw = getattr(cls, "category", None)
        grouped.setdefault(raw if isinstance(raw, str) else None, []).append(cls)

    lines = [
        BANNER,
        "",
        "# Features",
        "",
        f"{len(FEATURES)} features are registered. Each one runs as",
        "`mosaic run --feature <name>` and constructs directly in a notebook, and the",
        "parameter tables below are the same JSON-Schema that",
        "`mosaic features describe <name> --json` prints.",
        "",
        "Every run is addressed by `<version>-<hash of params, inputs and frame range>`,",
        "so the version column is what a bump moves: change it and every run of that",
        "feature re-addresses.",
        "",
        *TABLE_LEGEND,
    ]
    for category, title in CATEGORY_TITLES:
        members = sorted(
            grouped.get(category, ()), key=lambda c: str(getattr(c, "name", ""))
        )
        if not members:
            continue
        lines += [f"## {title}", ""]
        if category is None:
            lines += [UNCATEGORIZED_NOTE, ""]
        for cls in members:
            slug = getattr(cls, "name", cls.__name__)
            version = getattr(cls, "version", "0.0")
            lines += [
                f"### `{slug}`",
                "",
                f"Version `{version}` &middot; `{cls.__module__}.{cls.__qualname__}`",
                "",
            ]
            text = summary_line(cls)
            if text:
                lines += [text, ""]
            lines += params_table(cls.Params.model_json_schema())
    return "\n".join(lines).rstrip() + "\n"


def render_ops() -> str:
    from mosaic.core.pipeline.ops import OPS
    from mosaic.tracking import register_ops

    register_ops()

    grouped: dict[str, dict[str, list[type]]] = {}
    for cls in OPS.values():
        domain = str(getattr(cls, "domain", "tracking"))
        category = str(getattr(cls, "category", ""))
        grouped.setdefault(domain, {}).setdefault(category, []).append(cls)

    lines = [
        BANNER,
        "",
        "# Ops",
        "",
        f"{len(OPS)} ops are registered. An op is the unit `mosaic run --kind <kind>`",
        "executes: a tracker, a model training or inference run, a frame extraction, or",
        "a media operation. Features transform tables that already exist; ops are what",
        "produce them and what reaches outside the process.",
        "",
        '!!! note "Two of these are not discoverable from the CLI"',
        "",
        '    `mosaic tracking list` filters to `domain = "tracking"`, so the media ops',
        "    below appear in no discovery command even though `mosaic run --kind` runs",
        "    them. This page reads `OPS` directly and lists all of them.",
        "",
        *TABLE_LEGEND,
    ]
    for domain, title in DOMAIN_TITLES:
        by_category = grouped.get(domain)
        if not by_category:
            continue
        lines += [f"## {title}", ""]
        for category in sorted(by_category):
            members = sorted(
                by_category[category], key=lambda c: str(getattr(c, "kind", ""))
            )
            lines += [f"### {category}", ""]
            for cls in members:
                kind = getattr(cls, "kind", cls.__name__)
                version = getattr(cls, "version", "0.0")
                resource = getattr(cls, "resource_class", None)
                meta = f"Version `{version}` &middot; `{cls.__module__}.{cls.__qualname__}`"
                if resource:
                    meta += f" &middot; resource class `{resource}`"
                # `target` is deliberately absent. It is a method, not a value,
                # so rendering it prints `<function TrexOp.target at 0x...>` --
                # an address that moves on every interpreter run, which is what
                # first made `--check` fail against a file written minutes
                # earlier. Nothing about it belongs on a reference page anyway.
                lines += [f"#### `{kind}`", "", meta, ""]
                text = summary_line(cls)
                if text:
                    lines += [text, ""]
                lines += params_table(cls.Params.model_json_schema())
    return "\n".join(lines).rstrip() + "\n"


def render_track_formats() -> str:
    from mosaic.core.label_converter import (
        LABEL_CONVERTERS,
        ensure_label_converters_registered,
    )
    from mosaic.core.schema import TRACK_SCHEMAS
    from mosaic.core.track_converter import TRACK_CONVERTERS

    ensure_label_converters_registered()

    lines = [
        BANNER,
        "",
        "# Track formats, schemas and label formats",
        "",
        f"{len(TRACK_CONVERTERS)} track converters read a tracker's output into one of",
        f"{len(TRACK_SCHEMAS)} registered schemas, and {len(LABEL_CONVERTERS)} label",
        "converters read manual annotations. A converter declares the schema it emits,",
        "in one place, and that declaration is what validation and the tracks index",
        "both read.",
        "",
        "## Track converters",
        "",
        "Name a converter with `--src-format` on `mosaic sources add`, and it is applied",
        "by `mosaic convert-tracks`.",
        "",
        "| `src_format` | Version | Emits | Enumerable | Merges per sequence | What it reads |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for name in sorted(TRACK_CONVERTERS):
        cls = TRACK_CONVERTERS[name]
        lines.append(
            f"| `{name}` | `{getattr(cls, 'version', '')}` "
            f"| `{getattr(cls, 'output_schema', '')}` "
            f"| {'yes' if getattr(cls, 'enumerable', False) else 'no'} "
            f"| {'yes' if getattr(cls, 'merges_per_sequence', False) else 'no'} "
            f"| {escape_cell(summary_line(cls))} |"
        )
    lines += ["", "### Converter parameters", ""]
    for name in sorted(TRACK_CONVERTERS):
        cls = TRACK_CONVERTERS[name]
        lines += [f"#### `{name}`", ""]
        lines += params_table(cls.Params.model_json_schema())

    lines += [
        "## Track schemas",
        "",
        "Every schema validates a standardized parquet table. Spatial columns are video",
        "pixels and `X`/`Y` are the body center, except in the centimeter families,",
        "which say so in their names. A physical unit is otherwise obtained downstream",
        "by the `scale-to-cm` feature rather than stored in the table.",
        "",
    ]
    for name in sorted(TRACK_SCHEMAS):
        schema = TRACK_SCHEMAS[name]
        lines += [f"### `{name}`", ""]
        description = str(getattr(schema, "description", "") or "").strip()
        if description:
            lines += [description, ""]
        extends = getattr(schema, "extends", None)
        rows = [("Extends", f"`{extends}`" if extends else "nothing")]
        for label, attribute in (
            ("Required", "required"),
            ("Required prefixes", "required_prefixes"),
            ("Recommended", "recommended"),
            ("Allows", "allows"),
            ("Forbidden", "forbidden"),
        ):
            values = getattr(schema, attribute, None) or ()
            rendered = ", ".join(f"`{v}`" for v in sorted(str(v) for v in values))
            rows.append((label, rendered or "--"))
        lines += ["| | |", "| --- | --- |"]
        lines += [f"| {label} | {escape_cell(value)} |" for label, value in rows]
        lines.append("")

    lines += [
        "## Label converters",
        "",
        "Applied by `mosaic convert-labels --kind <label_kind>`.",
        "",
        "| Name | Label kind | What it reads |",
        "| --- | --- | --- |",
    ]
    for key in sorted(LABEL_CONVERTERS, key=lambda k: (str(k[0]), str(k[1]))):
        cls = LABEL_CONVERTERS[key]
        name, label_kind = key
        lines.append(
            f"| `{name}` | `{label_kind}` | {escape_cell(summary_line(cls))} |"
        )
    return "\n".join(lines).rstrip() + "\n"


def render_cli() -> str:
    """The whole `mosaic` command tree, from the Typer app itself.

    `typer.cli.get_docs_for_click` is what `typer <module> utils docs` calls. It
    is not a documented public API, so if it moves the fallback is that
    subprocess -- but taking it in process keeps the title and the program name
    under this script's control rather than a shell invocation's.

    The `mosaic media` group is contributed by the separate `mosaic-media`
    distribution, so its help text is not maintained in this repository and a
    release of that package can move this page. That is a true statement about
    the CLI a user gets, and `--check` naming it is the intended behaviour.
    """
    import typer
    from typer.cli import get_docs_for_click
    from typer.main import get_command

    from mosaic.cli import app

    command = get_command(app)
    context = typer.Context(command, info_name="mosaic")
    body = get_docs_for_click(obj=command, ctx=context, name="mosaic", title="CLI")
    return f"{BANNER}\n\n{body.strip()}\n"


def render_index() -> str:
    from mosaic.behavior.feature_library import FEATURES
    from mosaic.core.label_converter import (
        LABEL_CONVERTERS,
        ensure_label_converters_registered,
    )
    from mosaic.core.pipeline.ops import OPS
    from mosaic.core.schema import TRACK_SCHEMAS
    from mosaic.core.track_converter import TRACK_CONVERTERS
    from mosaic.tracking import register_ops

    register_ops()
    ensure_label_converters_registered()

    return (
        f"{BANNER}\n"
        "\n"
        "# What is where\n"
        "\n"
        "Every feature, op, command and format mosaic knows about, with the parameters\n"
        "each one takes. Reach for these when you know what you want to do and need the\n"
        "name and the knobs.\n"
        "\n"
        "| Page | Holds |\n"
        "| --- | --- |\n"
        f"| [Features](features.md) | {len(FEATURES)} registered features, "
        "grouped by category, with their parameters |\n"
        f"| [Ops](ops.md) | {len(OPS)} registered ops -- trackers, training, "
        "inference, frame extraction and media |\n"
        "| [CLI](cli.md) | Every `mosaic` command and flag |\n"
        f"| [Track formats](track-formats.md) | {len(TRACK_CONVERTERS)} track "
        f"converters, {len(TRACK_SCHEMAS)} schemas, {len(LABEL_CONVERTERS)} label "
        "converters |\n"
        "\n"
        "These four pages are generated from the registries themselves by\n"
        "`scripts/gen_docs_reference.py`. Continuous integration regenerates them and\n"
        "fails if the result differs from what is committed, so a count here cannot fall\n"
        "behind the code that produces it.\n"
        "\n"
        "## What a Python object takes\n"
        "\n"
        "Read its docstring, in the source or in an editor. There is no rendered API\n"
        "reference: the hand-written one reached under a third of the tree with nothing\n"
        "to keep it honest, so what it omitted read as absent from the toolkit.\n"
    )


PAGES: Final[dict[str, Callable[[], str]]] = {
    "index": render_index,
    "features": render_features,
    "ops": render_ops,
    "cli": render_cli,
    "track-formats": render_track_formats,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="Regenerate in memory and diff against what is committed (default).",
    )
    mode.add_argument(
        "--write", action="store_true", help="Write the pages to docs/reference/."
    )
    parser.add_argument(
        "--page",
        choices=sorted(PAGES),
        action="append",
        help="Limit to one page (repeatable).",
    )
    args = parser.parse_args()

    selected = args.page or sorted(PAGES)
    if args.write:
        REFERENCE_ROOT.mkdir(parents=True, exist_ok=True)

    stale: list[str] = []
    for name in selected:
        rendered = PAGES[name]()
        path = REFERENCE_ROOT / f"{name}.md"
        if args.write:
            path.write_text(rendered, encoding="utf-8")
            continue
        committed = path.read_text(encoding="utf-8") if path.exists() else ""
        if committed == rendered:
            continue
        stale.append(name)
        sys.stdout.writelines(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=f"{path.relative_to(REPOSITORY_ROOT)} (committed)",
                tofile=f"{path.relative_to(REPOSITORY_ROOT)} (regenerated)",
            )
        )

    if args.write:
        print(
            f"Wrote {len(selected)} page(s) to {REFERENCE_ROOT.relative_to(REPOSITORY_ROOT)}/"
        )
        return 0
    if stale:
        print(
            f"\n{len(stale)} generated page(s) out of date: {', '.join(stale)}.\n"
            "Run `python scripts/gen_docs_reference.py --write` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(f"{len(selected)} generated page(s) up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
